### ISSUE TITLE
README.PaaS.md should require a persistent storage

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#466]
https://github.com/frab/frab/blob/master/README.PaaS.md should also require a persistent volume for /home/frab/app/public (same as #461 ) ? I'm not familiar with Dokku .

**Comment by manno** [comment]
Apparently there is https://github.com/dokku/dokku/blob/master/docs/advanced-usage/persistent-storage.md
Maybe some dokku user can comment?

Would be nice to have Cloud Foundry instructions in that doc, too.

**Comment by almereyda** [comment]
We do not have Cloud Foundry, so I cannot explain this.

We have since moved from a Dokku deployment to a Docker Compose deployment, and are indeed mapping two host volumes into the container, which is missing from the PaaS documentation:

```
version: '2'
networks:
  frontend-web:
    external: true
  backend:
    driver: bridge

services:
  database:
    image: postgres:alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./postgres.env
    networks:
    - backend
    logging:
      driver: none
  app:
    build: ./src
    links:
      - database:postgresql
    volumes:
      - ./data:/usr/src/app/public/system
      - ./assets:/usr/src/app/public/assets
    env_file:
      - ./frontend.env
      - ./env
    networks:
      - frontend-web
      - backend
    logging:
      driver: none
```

It seems the instructions have been updated for Docker in #461 #462, but not for our Dokku case here. The Dokku instructions were also written for an old version of Dokku, and need to be revisited during our upcoming development deployments.
